#!/bin/bash
if [[ $(id -u) -ne 0 ]]; then
   echo "This script must be run as root"
   echo "re-run as \`sudo $0'"
   exit 1
fi

sudo pip3 install jsonschema
sudo apt install entr python3-oauth2client

echo -e "\nOK"