#!/bin/bash
# if [[ $(id -u) -ne 0 ]]; then
#    echo "This script must be run as root"
#    echo "re-run as \`sudo $0'"
#    exit 1
# fi

apt install entr python3-pip # python3-oauth2client
pip3 install --upgrade pickledb jsonschema certifi oauth2client rsa httplib2shim
pip  install --upgrade pickledb jsonschema certifi oauth2client rsa httplib2shim

echo -e "\nOK"
