#!/bin/bash

#function git-autopull {
  while :; do
    git pull | grep -v "Already up-to-date." | grep -v "fatal: unable to access"
    now=$(date -u +%s)
    fhn=$((now+500))
    echo "refreshing again at $(date --date="@$fhn" '+%H:%M:%S')"
    sleep 500
  done
#}
