#!/bin/bash
if [[ $(id -u) -ne 0 ]]; then
   echo "This script must be run as root"
   echo "re-run as \`sudo $0'"
   exit 1
fi

sudo apt-get install python3-pip # python3-oauth2client
sudo pip3 install jsonschema certifi oauth2client

echo -e "\nOK"