#!/bin/bash
port=99621
./server.py "$port" &
pid=$!
sleep 3
curl "localhost:$port" \
  -H "Origin: http://localhost:3000" \
  -H "Content-Type: application/json" \
  -XPOST -d '{
    "verb": "ping",
    "data": {
      "ping": "hello"
    },
      "time": {"conn_init": 1}
  }'
code=$?
sleep 5

trap 'kill -15 $pid; exit $code' EXIT INT TERM ERR
