#!/bin/bash
for filename in json/*; do
  name=$(python -c "print '$filename'.split('.')[0].split('/')[1]")
  echo -e "\n========== doing $name\n"
  tools/schematool validate "$name" "schema.json"
done